[package]
name = "widgets"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
egui-material-icons = { git = "https://github.com/lucasmerlin/egui-material-icons" }

[[example]]
name = "example"
path = "examples/example.rs"
